# 애플리케이션 이름
spring.application.name=api

# 서버 포트 설정 (리액트와 통신하기 위해 8082로 설정)
server.port=8082

# MariaDB 연결 정보
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/ourband?localInfile=true&authConfigurations=MariaDbPassword
spring.datasource.username=root
spring.datasource.password=wjdals1831

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# DB 타입을 확실히 알려줘서 Dialect 에러 방지
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# 데브툴즈 설정 (수정 시 자동 재시작)
spring.devtools.restart.enabled=true

#jwt 설정
jwt.secret=my-super-secret-key-for-ourband-project-123456
jwt.expiration=86400000

# Cloudflare R2 설정
cloud.cloudflare.r2.endpoint=https://83e0979d430a4d0e5e34e0977fc3ef9d.r2.cloudflarestorage.com
cloud.cloudflare.r2.access-key=3eabc10348b2a6c94aef117fbdf9d472
cloud.cloudflare.r2.secret-key=bb553467afddf97c7915a25a734182495e96881bad049b9f0ccd02dd22bdbe2c
cloud.cloudflare.r2.bucket-name=ourband-media