spring.application.name=api
server.port=8082

# MariaDB 연결 정보 (환경 변수로 주입받음)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# jwt 설정
jwt.secret=${JWT_SECRET:my-super-secret-key-for-ourband-project-123456}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# Cloudflare R2 설정
cloud.cloudflare.r2.endpoint=${R2_ENDPOINT:https://83e0979d430a4d0e5e34e0977fc3ef9d.r2.cloudflarestorage.com}
cloud.cloudflare.r2.access-key=${R2_ACCESS_KEY:3eabc10348b2a6c94aef117fbdf9d472}
cloud.cloudflare.r2.secret-key=${R2_SECRET_KEY:bb553467afddf97c7915a25a734182495e96881bad049b9f0ccd02dd22bdbe2c}
cloud.cloudflare.r2.bucket-name=${R2_BUCKET_NAME:ourband-media}

# Redis 설정 (환경 변수로 주입받음)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:wjdals1831@gmail.com}
spring.mail.password=${MAIL_PASSWORD:njjq argc tupi jwde}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Recaptcha
spring.recaptcha.secret-key=${RECAPTCHA_SECRET:6LcAiQgtAAAAAG2KPn88C7syBAYAExrdknyLc9xO}
