name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_TOKEN
          script: |
            cd ~/OurBand
            
            # 1. 최신 코드 가져오기
            git pull https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
            
            # 2. 백엔드 빌드 및 재시작 (Docker)
            cd api
            sudo docker compose up -d --build
            
            # 3. 프론트엔드 빌드 및 재시작 (PM2)
            cd ../front/ourband
            npm install
            npm run build
            pm2 restart all
